name: top-frontend
tenantId: 72fca1b1-2c2e-4376-a445-294d80196804

labels:
  app: top-frontend

image:
  registry: saks01weuacrpgpgo5qvmwo.azurecr.io
  tag: latest

network:
  allow-ingress:
    selector: app == 'top-frontend'
    ingress:
      - action: Allow
    egress:
      - action: Allow

serviceAccount: app
serviceAccounts:
  app: {}

secrets:
  certificate:
    type: keyvault
    tls: wonen

deployments:
  top-frontend:
    image:
      repository: salmagundi/top-frontend
    selectorLabels:
      component: top-frontend
    containers:
      - name: main
        ports:
          - port: 7000
            name: http
        volumes:
          - name: logs
            mountPath: /var/log/nginx
          - name: run
            mountPath: /var/run
          - name: cache
            mountPath: /var/cache/nginx
    volumes:
      - name: logs
        spec:
          emptyDir: {}
      - name: run
        spec:
          emptyDir: {}
      - name: cache
        spec:
          emptyDir: {}

services:
  top-frontend:
    selector:
      component: top-frontend
    ports:
      - port: 7000
        targetPort: http

ingress:
  top-frontend-internal:
    className: nginx-internal
    paths:
      - path: /
        pathType: Prefix
        service: top-frontend
        port: 7000
    tls: certificate

jobs:
  certificate-init:
    image:
      repository: salmagundi/top-frontend
    annotations:
      helm.sh/hook: post-install,post-upgrade
    labels:
      component: certificate
    secrets:
      - certificate
    containers:
      - name: main
        command:
          - sleep
        args:
          - "1"
